Shader "HoyoToon/Genshin Impact/Character/Uber/Base"
{
    Properties
    {
        [MainGroup(Main Settings)] _DummyMainSettings ("Main Settings", Float) = 0
        [SubGroup(Main Settings)] _ElementViewEleID ("$en$:Element ID $cn$:元素视野ID", Float) = 0
        [SubMHYToggle(Main Settings)] _UseMaskInShadowExport ("$en$:Use Mask In Shadow Export $cn$:在导出PV阴影时使用遮罩", Float) = 0
        [SubMHYToggle(Main Settings)] _UsePVMask1 ("$en$:Use PV Mask 1 $cn$:使用PV遮罩1", Float) = 0
        [SubGroup(Main Settings)] [NoScaleOffset] _PVMask1 ("$en$:PV Mask 1 (R Eyelashe, G White Eye, B Eyebrow, A Pupil) $cn$:PV用遮罩1（R睫毛，G眼白，B眉毛，A瞳孔）", 2D) = "black" { }
        [SubMHYToggle(Main Settings)] _UsePVMask2 ("$en$:Use PV Mask 2 $cn$:使用PV遮罩2", Float) = 0
        [SubGroup(Main Settings)] [NoScaleOffset] _PVMask2 ("$en$:PV Mask 2 (R Mouth, G Teeth) $cn$:PV用遮罩2（R口腔，G牙齿）", 2D) = "black" { }
        [SubMHYToggle(Main Settings)] _FlareType ("$en$:Flare Type (When causing flare) $cn$:光晕设置", Float) = 0
        [SubMHYToggle(Main Settings)] _UseNPCMultiEye ("$en$:Use NPC MultiEye $cn$:使用NPC多眼模式", Float) = 0
        [SubEnum(Main Settings, Big, 0, Mid, 1, Small, 2)] _NPCMultiEyeSize ("$en$:NPC Eye Size $cn$:NPC眼睛大小", Float) = 0
        [MainGroup(Character MainTex)] _CharacterMainTex ("Character Main Texture", Float) = 0
        [SubGroup(Character MainTex)] _MainTex ("$en$:Main Tex $cn$:主贴图", 2D) = "white" { }
        [SubEnum(Character MainTex, None, 0, AlphaTest, 1, Emission, 2, FaceBlush, 3)] _MainTexAlphaUse ("$en$:Main Tex Alpha Use $cn$:主贴图透明度使用方式", Float) = 0
        [SubGroup(Character MainTex)] _MainTexAlphaCutoff ("$en$:Main Tex Alpha Cutoff $cn$:主贴图透明度剔除", Range(0, 1)) = 0.5
        [SubGroup(Character MainTex)] _FaceBlushStrength ("$en$:Face Blush Strength $cn$:脸红强度", Range(0, 1)) = 0
        [SubGroup(Character MainTex)] _FaceBlushColor ("$en$:Face Blush Color $cn$:脸红颜色", Color) = (1,0.8,0.7,1)
        [SubGroup(Character MainTex)] _Color ("$en$:Tint Color 1 $cn$:材质1的染色颜色", Color) = (1,1,1,1)
        [SubMHYToggle(Character MainTex)] _UseEyeMask ("$en$:Use Eye Mask Clip $cn$:使用眼睛遮罩剔除", Float) = 0
        [SubGroup(Character MainTex)] [NoScaleOffset] _EyeMask ("$en$:Eye Mask (R) $cn$:眼睛遮罩剔除 （R）", 2D) = "white" { }
        [SubGroup(Character MainTex)] _HairTransparentValue ("$en$:Hair Transparent Value $cn$:头发透明度", Range(0, 1)) = 0.5
        [SubMHYToggle(Character MainTex)] _UseHairAlphaLimitation ("$en$:Use Hair Alpha Limitation $cn$:使用眼睛透明度角度限制", Float) = 0
        [SubMHYRemap01Slider(Character MainTex)] _HairTransRemapHori ("$en$:Hair Transparent Limitation Horizontal $cn$:头发透明度角度水平限制", Vector) = (0.8,1,1,0)
        [SubMHYRemap01Slider(Character MainTex)] _HairTransRemapVert ("$en$:Hair Transparent Limitation Vertical $cn$:头发透明度角度竖直限制", Vector) = (0.4,0.8,1,0)
        [SubGroup(Character MainTex)] _HairShadowLightShift ("$en$:Hair Shadow Light Shift $cn$:头发阴影受光偏移", Range(0, 3)) = 0.7
        [SubMHYRemap01Slider(Character MainTex)] _HairShadowVerticalRemap ("$en$:Hair Shadow Vertical Remap $cn$:头发阴影竖直限制", Vector) = (0,1,1,0)
        [SubGroup(Character MainTex)] _HairShadowStencilShift ("$en$:Hair Shadow Shift $cn$:头发阴影偏移", Vector) = (0,0,0,0)
        [SubMHYToggle(Character MainTex)] _UseHairAlphaMask ("$en$:Use Hair Alpha Mask With Bump B $cn$:使用Bump B通道标记透眼范围", Float) = 0
        [SubGroup(Character MainTex)] _HairShadowExtrusion ("$en$:Hair Shadow Extrusion $cn$:头发阴影挤压", Range(0, 2)) = 1
        [SubEnum(Character MainTex, UnityEngine.Rendering.BlendMode)] _HairSrcBlendMode ("$en$:Hair Src Blend Mode $cn$:头发来源混合模式", Float) = 5
        [SubEnum(Character MainTex, UnityEngine.Rendering.BlendMode)] _HairDstBlendMode ("$en$:Hair Dst Blend Mode $cn$:头发目标混合模式", Float) = 10
        [SubEnum(Character MainTex, UnityEngine.Rendering.BlendOp)] _HairBlendOP ("$en$:Hair Blend Op Mode $cn$:头发混合操作模式", Float) = 0
        [SubGroup(Character MainTex)] _DesaturateScale ("$en$:Desaturate Scale $cn$:去饱和程度", Range(0, 1)) = 0
        [MainGroup(Material Masks, MATERIAL_MASK)] _UseMaterialMasksTex ("Material Masks", Float) = 0
        [SubGroup(Material Masks)] _MaterialMasksTex ("$en$:Material Masks $cn$:材质球遮罩", 2D) = "black" { }
        [MainGroup(Light Map, TOON_LIGHTMAP_ON)] _UseToonLightMap ("Light Map", Float) = 0
        [SubMHYToggle(Light Map)] _UseLightMapColorAO ("$en$:Use Light Map Color.g For AO $cn$:使用光照贴图的G通道用于制作AO", Float) = 1
        [SubGroup(Light Map)] [NoScaleOffset] _LightMapTex ("$en$:Light Map Tex (RGB) $cn$:光照贴图", 2D) = "gray" { }
        [MainGroup(Bump Map, BUMP_TEXTURELINE_MAP)] _UseBumpMap ("Bump Map", Float) = 0
        [SubGroup(Bump Map)] [NoScaleOffset] _BumpMap ("$en$:Bump Map(RG) SDF(B) $cn$:法线/线条加强（B通道）贴图", 2D) = "black" { }
        [SubGroup(Bump Map)] _BumpScale ("$en$:Bump Scale $cn$:法线贴图强度", Range(0.0001, 1)) = 1
        [SubMHYToggle(Bump Map)] _UseMobileBumpCompressSmooth ("$en$:Use Mobile Bump Compress Smooth $cn$:手机压缩后平滑", Float) = 0
        [MainGroup(Character Shadow)] _CharacterShadow ("Character Shadow", Float) = 0
        [SubGroup(Character Shadow)] _FirstShadowMultColor ("$en$:Warm Shadow Color 1 $cn$:材质1的暖色颜色", Color) = (0.9,0.7,0.75,1)
        [SubGroup(Character Shadow)] _CoolShadowMultColor ("$en$:Cool Shadow Color 1 $cn$:材质1的冷色颜色", Color) = (0.9,0.7,0.75,1)
        [SubMHYToggle(Character Shadow)] _UseVertexColorAO ("$en$:Use Vertex Color.r For AO $cn$:使用顶点色的R通道用于制作AO", Float) = 1
        [SubMHYToggle(Character Shadow)] _UseCoolShadowColorOrTex ("$en$:Use Cool Shadow Color Or Tex $cn$:使用冷色阴影颜色或者贴图", Float) = 0
        [SubGroup(Character Shadow)] _LightArea ("$en$:Light Area Threshold $cn$:光照区域范围", Range(0, 1)) = 0.5
        [SubMHYToggle(Character Shadow)] _UseShadowTransition ("$en$:Use Shadow Transition (only work when shadow ramp is off) $cn$:使用阴影过渡（仅在阴影渐变关闭时有效）", Float) = 0
        [SubGroup(Character Shadow)] _ShadowTransitionRange ("$en$:Shadow Transition Range 1 $cn$:材质1的阴影过渡范围", Range(0.001, 0.2)) = 0.01
        [SubGroup(Character Shadow)] _ShadowTransitionSoftness ("$en$:Shadow Transition Softness 1 $cn$:材质1的阴影过渡柔软程度", Range(0, 2)) = 0.5
        [MainGroup(Shadow Ramp, SHADOW_RAMP_ON)] _UseShadowRamp ("Shadow Ramp", Float) = 0
        [SubMHYPackedGradient(Shadow Ramp, _ShadowRampTex1 _ShadowRampTex2 _ShadowRampTex3 _ShadowRampTex4 _ShadowRampTex5 _CoolShadowRampTex1 _CoolShadowRampTex2 _CoolShadowRampTex3 _CoolShadowRampTex4 _CoolShadowRampTex5)] _PackedShadowRampTex ("$en$:Packed Shadow Ramp Tex $cn$:合并的阴影渐变贴图", 2D) = "grey" { }
        [SubGroup(Shadow Ramp)] _ShadowRampWidth ("$en$:Shadow Ramp Width $cn$:阴影渐变宽度", Range(0.01, 10)) = 1
        [SubMHYToggle(Shadow Ramp)] _UseVertexRampWidth ("$en$:Use Vertex Shadow Ramp Width $cn$:使用顶点引用渐变宽度", Float) = 0
        [SubGroup(Shadow Ramp)] _useShadowSoft ("$en$:use ShadowSoft? $cn$:是否使用软阴影", Range(0, 1)) = 0
        [SubGroup(Shadow Ramp)] _shadowSoftRange ("$en$:shadow SoftRange $cn$:软阴影过度范围", Range(0, 2)) = 1
        [MainGroup(Character Specular)] _UseSpecular ("Character Specular", Float) = 0
        [SubGroup(Character Specular)] _Shininess ("$en$:Specular Shininess 1 $cn$:材质1的高光范围", Range(0.1, 100)) = 10
        [SubGroup(Character Specular)] _SpecMulti ("$en$:Specular Multiply Factor 1 $cn$:材质1的高光强度", Range(0, 1)) = 0.1
        [SubGroup(Character Specular)] _SpecualrInShaow ("$EN$:Specular in Shadow $CN$:阴影下的高光强度", Range(0, 1)) = 0
        [SubGroup(Character Specular)] [HDR] _SpecularColor ("$en$:Specular Color 1 $cn$:材质1高光颜色", Color) = (1,1,1,1)
        [SubGroup(Character Specular)] _SpecOpacity ("$en$:Specular Opacity 1 $cn$:材质1高光透明度", Range(0, 1)) = 0
        [MainGroup(Character PlaneClips, ENABLE_CHARACTER_PLANECLIPS_ON)] _UseCharacterPlaneClips ("Character PlaneClips", Float) = 0
        [MainGroup(Metal Material, METAL_MAT)] _MetalMaterial ("Metal Material", Float) = 0
        [SubGroup(Metal Material)] _MTMap ("$en$:Metal Map $cn$:金属贴图", 2D) = "white" { }
        [SubGroup(Metal Material)] _MTMapBrightness ("$en$:Metal Map Brightness $cn$:金属贴图亮度", Float) = 1
        [SubGroup(Metal Material)] _MTMapTileScale ("$en$:Metal Map Tile Scale $cn$:金属贴图平铺尺寸", Float) = 1
        [SubGroup(Metal Material)] [HDR] _MTMapLightColor ("$en$:Metal Map Light Color $cn$:金属贴图亮部颜色", Color) = (1,1,1,1)
        [SubGroup(Metal Material)] [HDR] _MTMapDarkColor ("$en$:Metal Map Dark Color $cn$:金属贴图暗部颜色", Color) = (0,0,0,0)
        [SubGroup(Metal Material)] _MTShadowMultiColor ("$en$:Metal Shadow Multiply Color $cn$:金属阴影叠加颜色", Color) = (0.8,0.8,0.8,0.8)
        [SubGroup(Metal Material)] _MTShininess ("$en$:Metal Shininess $cn$:金属高光范围", Float) = 11
        [SubGroup(Metal Material)] _MTSpecularScale ("$en$:Metal Specular Scale $cn$:金属高光强度", Float) = 60
        [SubGroup(Metal Material)] _MTSpecularAttenInShadow ("$en$:Metal Specular Attenuation in Shadow $cn$:阴影中的金属高光衰减", Range(0, 1)) = 0.2
        [SubGroup(Metal Material)] [HDR] _MTSpecularColor ("$en$:Metal Specular Color $cn$:金属高光颜色", Color) = (1,1,1,1)
        [SubMHYToggle(Metal Material)] _MTUseSpecularRamp ("$en$:Use Metal Specular Ramp $cn$:使用金属高光渐变", Float) = 0
        [SubMMDGradient(Metal Material)] _MTSpecularRamp ("$en$:Specular Ramp $cn$:金属高光渐变贴图", 2D) = "grey" { }
        [SubGroup(Metal Material)] _MTSharpLayerOffset ("$en$:Sharp Highlight Offset $cn$:锐化高亮偏移", Range(0.001, 1)) = 1
        [SubGroup(Metal Material)] [HDR] _MTSharpLayerColor ("$en$:Sharp High Light Color $cn$:锐化高亮颜色", Color) = (1,1,1,1)
        [SubGroup(Metal Material)] _MTSpecularOffset ("$en$:Specular  Offset $cn$:高亮偏移", Range(0, 1)) = 0
        [SubGroup(Metal Material)] _MTSpecularShadowScale ("$en$:MTSpecular ShadowScale $cn$:高亮暗部强度", Range(0, 1)) = 0
        [SubMHYToggle(Metal Material)] _MTSpecularAO ("$en$:Specular Affected by AO $cn$:高光受AO影响", Float) = 0
        [MainGroup(Character Emission)] _CharacterEmission ("Character Emission", Float) = 0
        [SubGroup(Character Emission)] _EmissionScaler ("$en$:Emission Scaler $cn$:自发光强度", Range(0, 100)) = 1
        [HideInInspector] _EmissionScaler_State ("", Vector) = (0,0,0,0)
        [HideInInspector] _EmissionScaler_Value1 ("", Vector) = (0,0,0,0)
        [HideInInspector] _EmissionScaler_Value2 ("", Vector) = (0,0,0,0)
        [HideInInspector] _EmissionScaler_LerpParam ("", Vector) = (0,0,0,0)
        [SubGroup(Character Emission)] _EmissionColor_MHY ("$en$:Emission Color $cn$:自发光颜色", Color) = (1,1,1,1)
        [SubGroup(Character Emission)] [HDR] _EmissionColor_MHY1 ("$en$:Emission Color 1 $cn$:材质1自发光颜色", Color) = (1,1,1,1)
        [SubGroup(Character Emission)] _EmissionScaler1 ("$en$:Emission Scaler 1 $cn$:材质1的自发光强度", Range(0, 100)) = 1
        [SubMHYToggle(Character Emission)] _EnableEmissionBloom ("$en$:Outline EnableEmission $cn$:允许泛光", Float) = 0
        [SubGroup(Character Emission)] [HDR] _EmissionBloomColor ("$en$:Outline EmissionColor $cn$:泛光颜色", Color) = (1,1,1,1)
        [SubGroup(Character Emission)] _EmissionBloomScale ("$en$:Outline EmissionScale $cn$:泛光强度", Range(0, 5)) = 1.3
        [MainGroup(Texture Line, ENABLE_TEXTURE_LINE_ON)] _DummyTextureLine ("Texture Line", Float) = 0
        [SubGroup(Texture Line)] _TextureLineThickness ("$en$:Texture Line Thickness $cn$:轮廓线厚度", Range(0, 1)) = 0.6
        [SubGroup(Texture Line)] _TextureLineSmoothness ("$en$:Texture Line Smoothness $cn$:轮廓线平滑度", Range(0, 0.5)) = 0.1
        [SubGroup(Texture Line)] _TextureLineDistanceControl ("$en$:Thickness Inc/Max, smooth start Depth $cn$:轮廓线厚度最小值最大值、平滑开始的深度", Vector) = (0.1,0.6,1,1)
        [SubGroup(Texture Line)] [HDR] _TextureLineMultiplier ("$en$:Texture Line Multiplier $cn$:轮廓线强度", Color) = (1,1,1,1)
        [MainGroup(Outline)] _DummyOutline ("Outline", Float) = 0
        [SubGroup(Outline)] _OutlineWidth ("$en$:Outline Width 1 $cn$:材质1描边宽度", Range(0, 100)) = 0.04
        [SubGroup(Outline)] [HDR] _OutlineColor ("$en$:Outline Color $cn$:描边颜色", Color) = (0,0,0,1)
        [SubGroup(Outline)] _OutLineZOffset ("$en$:OutLine Back Face Z Offset $cn$:描边背面Z偏移", Range(0, 0.1)) = 0
        [SubGroup(Outline)] _OutLineIntensity ("$en$:Outline With Albedo $cn$:勾边颜色受主贴图颜色影响程度", Range(0, 1)) = 0
        [SubGroup(Outline)] _MaxOutlineZOffset ("$en$:Max Outline Z Offset $cn$:最大描边Z偏移", Range(0, 100)) = 1
        [SubMHYToggle(Outline)] _OutlineOffsetBlockBChannel ("$en$:Offset Block B Channel $cn$:屏蔽顶点色B通道影响偏移", Float) = 0
        [SubGroup(Outline)] _OutlineWidthAdjustZs ("$en$:Outline Width Adjust Dist Start (near, middle, far) $cn$:描边宽度开始距离（近中远）", Vector) = (0.01,2,6,0)
        [SubGroup(Outline)] _OutlineWidthAdjustScales ("$en$:Outline Width Adjust Scale (near, middle, far) $cn$:描边宽度调整距离（近中远）", Vector) = (0.105,0.245,0.6,0)
        [MainGroup(Material 2)] _DummyMaterial2 ("Material 2", Float) = 0
        [SubMHYToggle(Material 2)] _UseMaterial2 ("$en$:Use Material 2 $cn$:使用材质2", Float) = 0
        [SubGroup(Material 2)] _Color2 ("$en$:Tint Color 2 $cn$:材质2染色颜色", Color) = (1,1,1,1)
        [SubGroup(Material 2)] _EmissionScaler2 ("$en$:Emission Scaler 2 $cn$:材质2自发光强度", Range(0, 100)) = 1
        [SubGroup(Material 2)] [HDR] _EmissionColor_MHY2 ("$en$:Emission Color 2 $cn$:材质2自发光部分颜色", Color) = (1,1,1,1)
        [SubGroup(Material 2)] _FirstShadowMultColor2 ("$en$:Warm Shadow Color 2 $cn$:材质2暖色颜色", Color) = (0.9,0.7,0.75,1)
        [SubGroup(Material 2)] _CoolShadowMultColor2 ("$en$:Cool Shadow Color 2 $cn$:材质2冷色颜色", Color) = (0.9,0.7,0.75,1)
        [SubGroup(Material 2)] _Shininess2 ("$en$:Specular Shininess 2 $cn$:材质2高光范围", Range(0.1, 100)) = 10
        [SubGroup(Material 2)] _SpecMulti2 ("$en$:Specular Multiply Factor 2 $cn$:材质2高光强度", Range(0, 1)) = 0.1
        [SubGroup(Material 2)] _SpecOpacity2 ("$en$:Specular Opacity 2 $cn$:材质2高光透明度", Range(0, 1)) = 0
        [SubGroup(Material 2)] [HDR] _SpecularColor2 ("$en$:Specular Color 2 $cn$:材质2高光颜色", Color) = (1,1,1,1)
        [SubGroup(Material 2)] [HDR] _CharacterCubeColor2 ("$en$:Character Cube Color 2 $cn$:材质2环境球颜色", Color) = (0,0,0,0)
        [SubGroup(Material 2)] _OutLineIntensity2 ("$en$:Outline Intensity 2  $cn$:材质2描边颜色受Diffuse影响", Range(0, 1)) = 0
        [SubGroup(Material 2)] _OutlineColor2 ("$en$:Outline Color 2 $cn$:材质2描边颜色", Color) = (0,0,0,1)
        [SubGroup(Material 2)] _ShadowTransitionRange2 ("$en$:Shadow Transition Range 2 $cn$:材质2阴影过渡范围", Range(0.001, 0.2)) = 0.01
        [SubGroup(Material 2)] _ShadowTransitionSoftness2 ("$en$:Shadow Transition Softness 2 $cn$:材质2阴影过渡柔软程度", Range(0, 2)) = 0.5
        [SubGroup(Material 2)] _useShadowSoft2 ("$en$:ShadowMap Soft $cn$:使用软阴影", Range(0, 1)) = 0
        [SubGroup(Material 2)] _shadowSoftRange2 ("$en$:ShadowMap SoftRange $cn$:使用软阴影过度", Range(0, 2)) = 0
        [MainGroup(Material 3)] _DummyMaterial3 ("Material 3", Float) = 0
        [SubMHYToggle(Material 3)] _UseMaterial3 ("$en$:Use Material 3 $cn$:使用材质3", Float) = 0
        [SubGroup(Material 3)] _Color3 ("$en$:Tint Color 3 $cn$:材质3染色颜色", Color) = (1,1,1,1)
        [SubGroup(Material 3)] _EmissionScaler3 ("$en$:Emission Scaler 3 $cn$:材质3自发光强度", Range(0, 100)) = 1
        [SubGroup(Material 3)] [HDR] _EmissionColor_MHY3 ("$en$:Emission Color 3 $cn$:材质3自发光部分颜色", Color) = (1,1,1,1)
        [SubGroup(Material 3)] _FirstShadowMultColor3 ("$en$:Warm Shadow Multiply Color 3 $cn$:材质3暖色颜色", Color) = (0.9,0.7,0.75,1)
        [SubGroup(Material 3)] _CoolShadowMultColor3 ("$en$:Cool Shadow Multiply Color 3 $cn$:材质3冷色颜色", Color) = (0.9,0.7,0.75,1)
        [SubGroup(Material 3)] _Shininess3 ("$en$:Specular Shininess 3 $cn$:材质3高光范围", Range(0.1, 100)) = 10
        [SubGroup(Material 3)] _SpecMulti3 ("$en$:Specular Multiply Factor 3 $cn$:材质3高光强度", Range(0, 1)) = 0.1
        [SubGroup(Material 3)] _SpecOpacity3 ("$en$:Specular Opacity 3 $cn$:材质3高光透明度", Range(0, 1)) = 0
        [SubGroup(Material 3)] [HDR] _SpecularColor3 ("$en$:Specular Color 3 $cn$:材质3高光颜色", Color) = (1,1,1,1)
        [SubGroup(Material 3)] [HDR] _CharacterCubeColor3 ("$en$:Character Cube Color 3 $cn$:材质3环境球颜色", Color) = (0,0,0,0)
        [SubGroup(Material 3)] _OutLineIntensity3 ("$en$:Outline Intensity 3  $cn$:材质3描边颜色受Diffuse影响", Range(0, 1)) = 0
        [SubGroup(Material 3)] _OutlineColor3 ("$en$:Outline Color 3 $cn$:材质3描边颜色", Color) = (0,0,0,1)
        [SubGroup(Material 3)] _ShadowTransitionRange3 ("$en$:Shadow Transition Range 3 $cn$:材质3阴影过渡范围", Range(0.001, 0.2)) = 0.01
        [SubGroup(Material 3)] _ShadowTransitionSoftness3 ("$en$:Shadow Transition Softness 3 $cn$:材质3阴影过渡柔软程度", Range(0, 2)) = 0.5
        [SubGroup(Material 3)] _useShadowSoft3 ("$en$:ShadowMap Soft $cn$:使用软阴影", Range(0, 1)) = 0
        [SubGroup(Material 3)] _shadowSoftRange3 ("$en$:ShadowMap SoftRange $cn$:使用软阴影过度", Range(0, 2)) = 0
        [MainGroup(Material 4)] _DummyMaterial4 ("Material 4", Float) = 0
        [SubMHYToggle(Material 4)] _UseMaterial4 ("$en$:Use Material 4 $cn$:使用材质4", Float) = 0
        [SubGroup(Material 4)] _Color4 ("$en$:Tint Color 4 $cn$:材质4染色颜色", Color) = (1,1,1,1)
        [SubGroup(Material 4)] _EmissionScaler4 ("$en$:Emission Scaler 4 $cn$:材质4自发光强度", Range(0, 100)) = 1
        [SubGroup(Material 4)] [HDR] _EmissionColor_MHY4 ("$en$:Emission Color 4 $cn$:材质4自发光部分颜色", Color) = (1,1,1,1)
        [SubGroup(Material 4)] _FirstShadowMultColor4 ("$en$:Warm Shadow Multiply Color 4 $cn$:材质4暖色颜色", Color) = (0.9,0.7,0.75,1)
        [SubGroup(Material 4)] _CoolShadowMultColor4 ("$en$:Cool Shadow Multiply Color 4 $cn$:材质4冷色颜色", Color) = (0.9,0.7,0.75,1)
        [SubGroup(Material 4)] _Shininess4 ("$en$:Specular Shininess 4 $cn$:材质4高光范围", Range(0.1, 100)) = 10
        [SubGroup(Material 4)] _SpecMulti4 ("$en$:Specular Multiply Factor 4 $cn$:材质4高光强度", Range(0, 1)) = 0.1
        [SubGroup(Material 4)] _SpecOpacity4 ("$en$:Specular Opacity 4 $cn$:材质4高光透明度", Range(0, 1)) = 0
        [SubGroup(Material 4)] [HDR] _SpecularColor4 ("$en$:Specular Color 4 $cn$:材质4高光颜色", Color) = (1,1,1,1)
        [SubGroup(Material 4)] [HDR] _CharacterCubeColor4 ("$en$:Character Cube Color 4 $cn$:材质4环境球颜色", Color) = (0,0,0,0)
        [SubGroup(Material 4)] _OutLineIntensity4 ("$en$:Outline Intensity 4  $cn$:材质4描边颜色受Diffuse影响", Range(0, 1)) = 0
        [SubGroup(Material 4)] _OutlineColor4 ("$en$:Outline Color 4 $cn$:材质4描边颜色", Color) = (0,0,0,1)
        [SubGroup(Material 4)] _ShadowTransitionRange4 ("$en$:Shadow Transition Range 4 $cn$:材质4阴影过渡范围", Range(0.001, 0.2)) = 0.01
        [SubGroup(Material 4)] _ShadowTransitionSoftness4 ("$en$:Shadow Transition Softness 4 $cn$:材质4阴影过渡柔软程度", Range(0, 2)) = 0.5
        [SubGroup(Material 4)] _useShadowSoft4 ("$en$:ShadowMap Soft $cn$:使用软阴影", Range(0, 1)) = 0
        [SubGroup(Material 4)] _shadowSoftRange4 ("$en$:ShadowMap SoftRange $cn$:使用软阴影过度", Range(0, 2)) = 0
        [MainGroup(Material 5)] _DummyMaterial5 ("Material 5", Float) = 0
        [SubMHYToggle(Material 5)] _UseMaterial5 ("$en$:Use Material 5 $cn$:使用材质5", Float) = 0
        [SubGroup(Material 5)] _Color5 ("$en$:Tint Color 5 $cn$:材质5染色颜色", Color) = (1,1,1,1)
        [SubGroup(Material 5)] _EmissionScaler5 ("$en$:Emission Scaler 5 $cn$:材质5自发光强度", Range(0, 100)) = 1
        [SubGroup(Material 5)] [HDR] _EmissionColor_MHY5 ("$en$:Emission Color 5 $cn$:材质5自发光部分颜色", Color) = (1,1,1,1)
        [SubGroup(Material 5)] _FirstShadowMultColor5 ("$en$:Warm Shadow Multiply Color 5 $cn$:材质5暖色颜色", Color) = (0.9,0.7,0.75,1)
        [SubGroup(Material 5)] _CoolShadowMultColor5 ("$en$:Cool Shadow Multiply Color 5 $cn$:材质5冷色颜色", Color) = (0.9,0.7,0.75,1)
        [SubGroup(Material 5)] _Shininess5 ("$en$:Specular Shininess 5 $cn$:材质5高光范围", Range(0.1, 100)) = 10
        [SubGroup(Material 5)] _SpecMulti5 ("$en$:Specular Multiply Factor 5 $cn$:材质5高光强度", Range(0, 1)) = 0.1
        [SubGroup(Material 5)] _SpecOpacity5 ("$en$:Specular Opacity 5 $cn$:材质5高光透明度", Range(0, 1)) = 0
        [SubGroup(Material 5)] [HDR] _SpecularColor5 ("$en$:Specular Color 5 $cn$:材质5高光颜色", Color) = (1,1,1,1)
        [SubGroup(Material 5)] [HDR] _CharacterCubeColor5 ("$en$:Character Cube Color 5 $cn$:材质5环境球颜色", Color) = (0,0,0,0)
        [SubGroup(Material 5)] _OutLineIntensity5 ("$en$:Outline Intensity 5  $cn$:材质5描边颜色受Diffuse影响", Range(0, 1)) = 0
        [SubGroup(Material 5)] _OutlineColor5 ("$en$:Outline Color 5 $cn$:材质5描边颜色", Color) = (0,0,0,1)
        [SubGroup(Material 5)] _ShadowTransitionRange5 ("$en$:Shadow Transition Range 5 $cn$:材质5阴影过渡范围", Range(0.001, 0.2)) = 0.01
        [SubGroup(Material 5)] _ShadowTransitionSoftness5 ("$en$:Shadow Transition Softness 5 $cn$:材质5阴影过渡柔软程度", Range(0, 2)) = 0.5
        [SubGroup(Material 5)] _useShadowSoft5 ("$en$:ShadowMap Soft $cn$:使用软阴影", Range(0, 1)) = 0
        [SubGroup(Material 5)] _shadowSoftRange5 ("$en$:ShadowMap SoftRange $cn$:使用软阴影过度", Range(0, 2)) = 0
        [MainGroup(Face Map, FACE_MAP_NEW_ON)] _UseFaceMapNew ("Face Map", Float) = 0
        [SubGroup(Face Map)] [NoScaleOffset] _FaceMapTex ("$en$:Face Map Tex (A Linear) $cn$:脸部贴图", 2D) = "gray" { }
        [SubGroup(Face Map)] _FaceMapRotateOffset ("$en$:Face Map Rotate Offset $cn$:脸部贴图旋转偏移", Range(-1, 1)) = 0
        [SubGroup(Face Map)] _FaceMapSoftness ("$en$:Face Map Softness $cn$:脸部贴图柔软程度", Range(1E-06, 1)) = 1E-06
        [MainGroup(Hair Map, HAIR_MAP_ON)] _UseHairMap ("Hair Map", Float) = 0
        [SubMHYToggle(Hair Map)] _UseBumpAsAOMask ("$en$:Use Bump.r as AO $cn$:将法线R用作AO遮罩", Float) = 0
        [SubGroup(Hair Map)] _AOShadowWarpScale ("$en$:AO ShadowWarpScale $cn$:AO阴影扰动强度", Range(0, 1)) = 1
        [SubEnum(Hair Map, All, 0, Mat1, 1, Mat2, 2, Mat3, 3, Mat4, 4, Mat5, 5)] _SelectMatID ("$en$:Select MatID $cn$:选择启用的MatID分区", Float) = 0
        [MainGroup(Back Face, BACK_FACE_ON)] _DrawBackFace ("Back Face", Float) = 0
        [SubMHYToggle(Back Face)] _UseBackFaceUV2 ("$en$:Use Back Face UV 2 $cn$:使用背面UV2", Float) = 1
        [SubMHYToggle(Back Face)] _BackFaceAlphaClipWithUV1 ("$en$:Back Face Alpha Clip With UV 1 $cn$:背面透贴使用UV1", Float) = 0
        [SubMHYToggle(Back Face)] _BackFaceLighting ("$en$:Back Face Lighting $cn$:背面光照", Float) = 0
        [MainGroup(Main Texture Tint, MAIN_TEX_COLORING_ON)] _MainTexColoring ("Main Texture Tint", Float) = 0
        [SubGroup(Main Texture Tint)] [HDR] _MainTexTintColor ("$en$:Main Tex Tint Color $cn$:主贴图染色颜色", Color) = (1,1,1,1)
        [MainGroup(Hit Color)] _DummyHitColor ("Hit Color", Float) = 0
        [SubGroup(Hit Color)] _HitColor ("$en$:Hit Color $cn$:打击颜色", Color) = (0,0,0,0)
        [SubGroup(Hit Color)] _ElementRimColor ("$en$:Element Rim Color $cn$:打击边缘光颜色", Color) = (0,0,0,0)
        [SubGroup(Hit Color)] _HitColorScaler ("$en$:Hit Color Scaler $cn$:打击颜色强度", Float) = 6
        [SubGroup(Hit Color)] _HitColorFresnelPower ("$en$:Hit Color Fresnel Power $cn$:打击颜色范围", Float) = 1.5
        [SubGroup(Hit Color)] _EmissionStrengthLerp ("$en$:Emission Strength Lerp $cn$:打击自发光颜色过度", Range(0, 1)) = 0
        [MainGroup(Use Dither)] _DummyUseDither ("Use Dither", Float) = 0
        [SubMHYToggle(Use Dither)] _UsingDitherAlpha ("$en$:Using Dither Alpha $cn$:使用透明度Dither", Float) = 0
        [SubGroup(Use Dither)] _DitherAlpha ("$en$:Dither Alpha Value $cn$:透明度Dither强度", Range(0, 1)) = 1
        [MainGroup(Use FakePoint, ENABLE_FAKEPOINT_ON)] _UseFakePoint ("Use FakePoint", Float) = 0
        [SubMHYToggle(Use FakePoint)] _EnableFakePoint ("$en$:Enable FakePoint $cn$:启用点光效果", Float) = 0
        [SubGroup(Use FakePoint)] _FakePointNoiseTex ("$en$:Fake PointNoiseTex $cn$:点光颜色", 2D) = "white" { }
        [SubGroup(Use FakePoint)] _FakePointColor ("$en$:Fake PointColor $cn$:点光颜色", Color) = (1,1,1,1)
        [SubGroup(Use FakePoint)] _FakePointRange ("$en$:Fake PointRange $cn$:点光范围", Float) = 1
        [SubGroup(Use FakePoint)] _FakePointIntensity ("$en$:Fake PointIntensity $cn$:点光强度", Float) = 1
        [SubGroup(Use FakePoint)] _FakePointPosition ("$en$:Fake PointPosition $cn$:点光位置", Vector) = (0,0,0,0)
        [SubGroup(Use FakePoint)] _FakePointReflection ("$en$:Fake PointReflection $cn$:点光反射强度", Float) = 1
        [SubGroup(Use FakePoint)] _FakePointFrequency ("$en$:Fake PointFrequency $cn$:点光频率", Float) = 0
        [SubGroup(Use FakePoint)] _FakePointFrequencyMin ("$en$:Fake PointFrequencyMin $cn$:点光频率最小值", Float) = 0
        [SubGroup(Use FakePoint)] _FakePointSkinIntensity ("$en$:Fake PointSkinIntensity $cn$:点光皮肤强度", Float) = 1
        [SubGroup(Use FakePoint)] _FakePointSkinSaturate ("$en$:Fake PointSkinSaturate $cn$:点光皮肤饱和度", Float) = 0
        [MainGroup(Texture Performance, ENABLE_PERFORMANCE_ON)] _EnablePerformance ("Enable Performance", Float) = 0
        [SubToggle(Texture Performance, ENABLE_PACK_LIGHT_ON)] _PackageLightMapToggle ("$en$:Package Light Map Toggle $cn$:合并光照贴图的开关", Float) = 0
        [SubEnum(Texture Performance, Layer1, 0, Layer2, 1, Layer3, 2)] _LightMapLayerEnum ("$en$:Light Map Layer Enum $cn$:选择当前光照贴图层数", Float) = 0
        [SubGroup(Texture Performance)] [NoScaleOffset] _PackageLightMap ("$en$:Package Light Map $cn$:三套光照贴图的图合并后的光照贴图", 2D) = "white" { }
        [SubGroup(Texture Performance)] [NoScaleOffset] _LightMapBlueNoise ("$en$:Blue Noise $cn$:蓝噪声", 2D) = "white" { }
        [SubGroup(Texture Performance)] _LightMapBlurSize ("$en$:Blur Size $cn$:模糊强度", Range(0, 10)) = 1
        [SubToggle(Texture Performance, ENABLE_PACK_NORMAL_ON)] _PackageNormalMapToggle ("$en$:Package Normal Map Toggle $cn$:合并法线贴图的开关", Float) = 0
        [SubEnum(Texture Performance, Layer1, 0, Layer2, 1, Layer3, 2)] _NormalMapLayerEnum ("$en$:Normal Map Layer Enum $cn$:选择当前法线贴图层数", Float) = 0
        [SubGroup(Texture Performance)] [NoScaleOffset] _NormalPackageMap ("$en$:Package Normal Map $cn$:合并后的法线贴图", 2D) = "white" { }
        [SubMHYToggle(Texture Performance)] _isNativeMainNormal ("$en$:Native Main Normal Toggle $cn$:高精度法线开关，将原始法线贴图存储在R、B通道上，不适用于三层", Float) = 0
        [SubGroup(Texture Performance)] _NormalMapOffset ("$en$:Normal Map Offset $cn$:优化后法线贴图采样偏移", Float) = 0
        [SubGroup(Texture Performance)] _NormalMapScale ("$en$:Normal Map Scale $cn$:优化后法线贴图采样强度", Float) = 0
        [SubGroup(Texture Performance)] [NoScaleOffset] _TextureLinePackageMap ("$en$:Texture Line Package Map $cn$:合并后的轮廓线贴图", 2D) = "black" { }
        [MainGroup(Fixed For Normal, 0)] _DummyFixedForNormal ("Fixed Normal", Float) = 0
        [MainGroup(NyxState MainSettings)] _MainSettingsGroup ("Nyx State Main Settings", Float) = 0
        [SubMHYPackedGradient(NyxState MainSettings, _NyxStateColorRamp _NyxStateTimeOfDayRamp)] _NyxStateOutlineColorRamp ("Color Ramp (RGB)", 2D) = "gray" { }
        [SubGroup(NyxState MainSettings)] _NyxStateOutlineColorScale ("Color Scale", Float) = 1
        [SubGroup(NyxState MainSettings)] _NyxStateOutlineColorOnBodyMultiplier ("OnBody Color Scale", Color) = (1,1,1,1)
        [SubGroup(NyxState MainSettings)] [NoScaleOffset] _NyxStateOutlineNoise ("Color and VertAnim Noise (RG)", 2D) = "gray" { }
        [SubVector2(NyxState MainSettings)] _NyxStateOutlineColorNoiseScale ("Color Noise Scale", Vector) = (2,2,0,0)
        [SubGroup(NyxState MainSettings)] _NyxStateOutlineColorNoiseAnim ("Color Noise Anim", Vector) = (0.05,0.05,0,0)
        [SubGroup(NyxState MainSettings)] _NyxStateOutlineColorNoiseTurbulence ("Color Noise Turbulence", Range(0, 1)) = 0.25
        [SubGroup(NyxState MainSettings)] [NoScaleOffset] _TempNyxStatePaintMaskTex ("Paint Mask", 2D) = "black" { }
        [SubEnum(NyxState MainSettings, R, 0, G, 1, B, 2, A, 3)] _TempNyxStatePaintMaskChannel ("Paint Mask Channel", Float) = 0
        [SubGroup(NyxState MainSettings)] _NyxStateOutlineColorOnBodyOpacity ("Paint Mask Multiplier", Range(0, 1)) = 1
        [MainGroup(NyxState Outline)] _OutlineGroup ("Nyx State Outline", Float) = 0
        [SubGroup(NyxState Outline)] _NyxStateOutlineWidthScale ("Width Scale", Float) = 5
        [SubVector3(NyxState Outline)] _NyxStateOutlineWidthVarietyWithResolution ("Variety with Resolution", Vector) = (1080,0,0,0)
        [SubMHYToggle(NyxState Outline)] _NyxStateEnableOutlineWidthScaleHeightLerp ("Enable Width Scale Height Lerp", Float) = 0
        [SubVector2(NyxState Outline)] _NyxStateOutlineWidthScaleRange ("Width Scale Lerp Range", Vector) = (1,1,0,0)
        [SubMHYRemap01Range(NyxState Outline)] _NyxStateOutlineWidthScaleLerpHeightRange ("Lerp Height Range", Vector) = (0,1,1,0)
        [SubVector2(NyxState Outline)] _NyxStateOutlineVertAnimNoiseScale ("VertAnim Noise Scale", Vector) = (2,2,0,0)
        [SubVector2(NyxState Outline)] _NyxStateOutlineVertAnimNoiseAnim ("VertAnim Noise Anim", Vector) = (0.05,0.05,0,0)
        [SubGroup(NyxState Outline)] _NyxStateOutlineVertAnimScale ("VertAnim Scale", Float) = 30
        [SubMHYToggle(NyxState Outline)] _NyxStateEnableOutlineVertAnimScaleHeightLerp ("Enable VertAnim Scale Height Lerp", Float) = 0
        [SubVector2(NyxState Outline)] _NyxStateOutlineVertAnimScaleRange ("VertAnim Scale Lerp Range", Vector) = (1,1,0,0)
        [SubMHYRemap01Range(NyxState Outline)] _NyxStateOutlineVertAnimScaleLerpHeightRange ("Lerp Height Range", Vector) = (0,1,1,0)
        [Dx11ShaderPerformance(DeferredUpdate)] _Dx11ShaderScore ("Dx11 Shader Score", Float) = 0
        [HideInInspector] _Dx11ShaderVsScore ("Dx11 Shader Vs Score", Float) = 0
        [HideInInspector] _Dx11ShaderPsScore ("Dx11 Shader Ps Score", Float) = 0
        [Header(Others)] _MHYZBias ("$en$:Z Bias $cn$:深度偏移（用于调整模型穿插）", Float) = 0
        _PolygonOffsetFactor ("$en$:Polygon Offset Factor $cn$:模型偏移因子", Float) = 0
        _PolygonOffsetUnit ("$en$:Polygon Offset Unit $cn$:模型偏移单位", Float) = 0
        _OutlinePolygonOffsetFactor ("$en$:Outline Polygon Offset Factor $cn$:描边模型偏移因子", Float) = 0
        _OutlinePolygonOffsetUnit ("$en$:Outline Polygon Offset Unit $cn$:描边模型偏移单位", Float) = 0
        [Enum(UnityEngine.Rendering.CullMode)] _CullMode ("$en$:Cull Mode $cn$:正反剔除方式", Float) = 2
        [Enum(UnityEngine.Rendering.CullMode)] _OutlineMotionVectorsCull ("$en$:Outline Motion Vector Cull Mode $cn$:描边运动向量正反剔除方式", Float) = 1
        [Space(10)] [Header(Depth Mode)] [Enum(Off, 0, On, 1)] _Zwrite ("$en$:ZWrite Mode $cn$:深度写入", Float) = 1
        [Enum(UnityEngine.Rendering.CompareFunction)] _Ztest ("$en$:Ztest Mode $cn$:深度测试", Float) = 4
        [Header(Blend Mode)] [Enum(UnityEngine.Rendering.BlendMode)] _SrcBlendMode ("$en$:Src Blend Mode $cn$:源混合参数", Float) = 1
        [Enum(UnityEngine.Rendering.BlendMode)] _DstBlendMode ("$en$:Dst Blend Mode $cn$:目标混合", Float) = 0
        [Enum(UnityEngine.Rendering.BlendOp)] _BlendOP ("$en$:BlendOp Mode $cn$:混合模式", Float) = 0
        _TransparentAlpha ("$en$:Transparent Alpha $cn$:透明度Alpha", Range(0, 1)) = 1
        [HideInInspector] _Scale ("Scale Compared", Float) = 0.01
        [HideInInspector] _TextureBiasWhenDithering ("Texture Bias When Dithering", Float) = -1
        [HideInInspector] _CharacterAmbientSensorShadowOn ("", Float) = 0
        [HideInInspector] _CharacterAmbientSensorForceShadowOn ("", Float) = 0
        [HideInInspector] _CharacterAmbientSensorColorOn ("", Float) = 0
        [HideInInspector] _EnableCustomParams ("Enable Custom Params", Float) = 0
        [HideInInspector] _EnableDistanceLerp ("Enable Distance Lerp", Float) = 0
        [HideInInspector] _SingleColorOutputColor ("Single Color Output Color", Color) = (1,1,1,1)
        [HideInInspector] _PlaneNormalVecU ("Plane Normal Vector U", Vector) = (0,0,0,0)
        [HideInInspector] _PlaneNormalVecV ("Plane Normal Vector V", Vector) = (0,0,0,0)
        [HideInInspector] _VSSKinningPoseTex ("VSSKinningPoseTex", 2D) = "black" { }
    }
}